[Feature] Benefit-notifications
associatedemployers/igneous pull request #384
Opened 2020-11-23 18:45 UTC by JavaLavaMT

WIP

2020-11-30 21:52 UTC, petersonbrock commented on lib/mail/templates/enrollment-confirmation/html.hbs
> +
empty lines could be cut out if you are feeling spicy

2020-11-30 21:52 UTC, petersonbrock commented on lib/mail/templates/hr_week-enrollments/html.hbs
> +
more empty lines, but only if you are feeling spicy

2020-11-30 21:52 UTC, petersonbrock commented on lib/mail/templates/hr_week-enrollments/html.hbs
> +                                  You have {{groups.new.length}} new {{inflect-text 'Enrollment' groups.new.length}}
I feel like the capitalization here could potentially be inconsistent.  "You have 3 new Enrollments and You Have 2 changes."

2020-11-30 21:52 UTC, petersonbrock commented on lib/mail/templates/hr_week-enrollments/transform-data.js
> +    let emp = await Employee.findById(enrollment.employee);
```suggestion
    let enrollment = data.enrollments[i],
        emp = await Employee.findById(enrollment.employee);
```

2020-11-30 21:52 UTC, petersonbrock commented on lib/mail/templates/open_enrollments-near/html.hbs
> +
ONLY IF FEELING SPICY

2020-11-30 21:52 UTC, petersonbrock commented on lib/tasks/notifications/benefits-eligible.js
> +      Notification    = require('../../models/notification');
me thinks use one const instead of two

2020-11-30 21:52 UTC, petersonbrock commented on lib/tasks/tests/open-enrollment.js
> +      today = 'you have an open enrollment starting today ',
```suggestion
      today = 'You have an open enrollment starting today',
```

2020-11-30 21:52 UTC, petersonbrock commented on lib/tasks/tests/open-enrollment.js
> +      nextMonth = 'You have an open enrollment starting next month ',
```suggestion
      nextMonth = 'You have an open enrollment starting next month',
```

2020-11-30 21:52 UTC, petersonbrock commented on lib/test-support/benefits-data/index.js
> +
extra line

2020-11-30 21:52 UTC, petersonbrock commented on lib/test-support/benefits-data/index.js
> +
here too

2020-11-30 21:59 UTC, James1x0 commented on lib/test-support/benefits-data/index.js
> +
Any reason why we are removing the name from the benefits data?

2020-12-01 14:26 UTC, JavaLavaMT commented on lib/test-support/benefits-data/index.js
> +
sorry copy-pasta on the selected line

2020-12-01 14:31 UTC, JavaLavaMT commented on lib/mail/templates/enrollment-confirmation/html.hbs
> +
🔥

2020-12-01 14:32 UTC, JavaLavaMT commented on lib/mail/templates/hr_week-enrollments/html.hbs
> +
🔥

2020-12-01 14:34 UTC, JavaLavaMT commented on lib/mail/templates/hr_week-enrollments/html.hbs
> +                                  You have {{groups.new.length}} new {{inflect-text 'Enrollment' groups.new.length}}
🏁

2020-12-01 14:39 UTC, JavaLavaMT commented on lib/tasks/notifications/benefits-eligible.js
> +      Notification    = require('../../models/notification');
🏁

2020-12-01 16:37 UTC, James1x0 requested changes

2020-12-01 16:37 UTC, James1x0 commented on config/tasks.json
> +  "Task :: HR Weekly Enrolment Notification": {
```suggestion
  "Task :: HR Weekly Enrollment Notification": {
```

2020-12-01 16:37 UTC, James1x0 commented on lib/mail/templates/hr_week-enrollments/html.hbs
> +                                  You have {{groups.new.length}} new {{inflect-text 'Enrollment' groups.new.length}}
```suggestion
                                  {{groups.new.length}} new {{inflect-text 'enrollment' groups.new.length}}
```

2020-12-01 16:37 UTC, James1x0 commented on lib/mail/templates/hr_week-enrollments/html.hbs
> +                                {{#if groups.new.length}}
```suggestion
                                You have
                                {{#if groups.new.length}}
```

2020-12-01 16:37 UTC, James1x0 commented on lib/mail/templates/hr_week-enrollments/html.hbs
> +                                  {{/if}}
```suggestion
                                  {{/if}}
```

2020-12-01 16:37 UTC, James1x0 commented on lib/mail/templates/hr_week-enrollments/html.hbs
> +                                  {{groups.change.length}} {{inflect-text 'Change' groups.change.length}}
```suggestion
                                  {{groups.change.length}} {{inflect-text 'change' groups.change.length}}  
```

2020-12-01 16:37 UTC, James1x0 commented on lib/mail/templates/hr_week-enrollments/html.hbs
> +                                <a href="http://granitehr.com/account/benefits/enrollments/enrollment{{change._id}}">{{change.emp.name.first}}</a> with a qualifying life event
```suggestion
                                <a href="http://granitehr.com/account/benefits/enrollments/enrollment/{{change._id}}">{{change.emp.name.first}}</a> with a qualifying life event
```

2020-12-01 16:37 UTC, James1x0 commented on lib/mail/templates/hr_week-enrollments/transform-data.js
> +        planTypes: enrollment.elections.map(elect=>elect.planType)
```suggestion
        planTypes: enrollment.elections.map(elect=> elect.planType)
```

2020-12-01 16:37 UTC, James1x0 commented on lib/mail/templates/hr_week-enrollments/transform-data.js
> +        planTypes: enrollment.elections.map(elect=>planNames[elect.planType])
```suggestion
        planTypes: enrollment.elections.map(elect=> planNames[elect.planType])
```

2020-12-01 16:37 UTC, James1x0 commented on lib/models/employee/methods/eligibilityNotification.js
> +  }
```suggestion

```
Impossible

2020-12-01 16:37 UTC, James1x0 commented on lib/models/employee/methods/eligibilityNotification.js
> +  let employee = await this.constructor.populate(this, { path: 'company' });
```suggestion
  const employee = await this.populate('company').execPopulate();
```

2020-12-01 16:37 UTC, James1x0 commented on lib/models/enrollment/middleware/notifications/completed.js
> +  if (!enrollment.isModified('signatureIP')) {
isModified in a post save [I think] doesn't work... Also we probably need a much better way of checking for completeness...

2020-12-01 16:37 UTC, James1x0 commented on lib/models/plan/methods/employeeIsEligible.js
> +  if (!employee.minimumHours || employee.minimumHours < this.minimumHours) {
```suggestion
  if ((employee.minimumHours || 0) < this.minimumHours) {
```

2020-12-01 16:37 UTC, James1x0 commented on lib/tasks/notifications/benefits-eligible.js
> +  const plans = await Plan.find();
![](https://media.giphy.com/media/3ELtfmA4Apkju/giphy.gif)

Just... all of them? Like... for all of the companies?

2020-12-01 16:37 UTC, James1x0 commented on lib/tasks/notifications/benefits-eligible.js
> +  await Employee.find({ $or: [{ terminatedOn: { $exists: false } }, { terminatedOn: null }] }).populate('company').cursor().eachAsync(async emp =>{
https://docs.mongodb.com/manual/tutorial/query-for-null-fields/#equality-filter
```suggestion
  await Employee.find({ terminatedOn: null }).populate('company').cursor().eachAsync(async (emp) => {
```

2020-12-01 16:37 UTC, James1x0 commented on lib/tasks/notifications/benefits-eligible.js
> +  await Employee.find({ $or: [{ terminatedOn: { $exists: false } }, { terminatedOn: null }] }).populate('company').cursor().eachAsync(async emp =>{
Refactor this to batch based on company. This can be seen in https://github.com/associatedemployers/igneous/blob/feature/%23320-edi-gen/lib/tasks/integrations/benefits-sync.js#L35-L55

2020-12-01 16:37 UTC, James1x0 commented on lib/tasks/notifications/benefits-eligible.js
> +    }
This will send out an email to eligible employees every time the task is ran...

2020-12-01 16:37 UTC, James1x0 commented on lib/tasks/notifications/hr-enrollment.js
> +
```suggestion
```

2020-12-01 16:37 UTC, James1x0 commented on lib/tasks/notifications/hr-enrollment.js
> +    $or:        [{ supersedes: null }, { supersedes: { $type: 7 } }]
I'm confused about this line. Supersedes is either null or an objectid. It seems like you're matching either which would make this query line inconsequential.

2020-12-01 16:37 UTC, James1x0 commented on lib/tasks/notifications/hr-enrollment.js
> +  }
Can you batch process these by company like mentioned in another task I reviewed?

2020-12-01 16:37 UTC, James1x0 commented on lib/tasks/notifications/open-enrollment.js
> +const debugPfx = 'Task :: OPEN ENROLLMENTS ::';
I see your all caps, I raise you a calm down

```suggestion
const debugPfx = 'Task :: Open Enrollments ::';
```

2020-12-01 16:37 UTC, James1x0 commented on lib/tasks/notifications/open-enrollment.js
> +  await Employee.find({ $or: [{ terminatedOn: { $exists: false } }, { terminatedOn: null }] }).populate('company').cursor().eachAsync(async emp =>{
```suggestion
  await Employee.find({ terminatedOn: null }).populate('company').cursor().eachAsync(async (emp) => {
```

2020-12-01 16:37 UTC, James1x0 commented on lib/tasks/notifications/open-enrollment.js
> +      let nearEnrollment = today || nextMonth ||  nextWeek || lastWeek;
🌟 I've seen this sort of thing approached differently, in a lot of different ways. I like this, and it feels more readable than big if blocks.

2020-12-01 16:37 UTC, James1x0 commented on lib/tasks/tests/benefits-eligible.js
> +      name:          'Very nice plan'
It's nice

2020-12-01 16:37 UTC, James1x0 commented on lib/tasks/tests/open-enrollment.js
> +  it('should send openEnrollment for today ', async () => {
```suggestion
  it('should send openEnrollment for today', async () => {
```

2020-12-01 16:37 UTC, James1x0 commented on lib/tasks/tests/open-enrollment.js
> +  it('should send openEnrollment for last week ', async () => {
```suggestion
  it('should send openEnrollment for last week', async () => {
```

2020-12-01 16:37 UTC, James1x0 commented on lib/tasks/tests/open-enrollment.js
> +  it('should send openEnrollment for next month ', async () => {
```suggestion
  it('should send openEnrollment for next month', async () => {
```

2020-12-01 16:37 UTC, James1x0 commented on lib/test-support/make-user/index.js
>    });
I wouldn't mind just having a company key in opts you spread here?

2020-12-02 20:07 UTC, JavaLavaMT commented on lib/tasks/notifications/benefits-eligible.js
> +  const plans = await Plan.find();
🏁

2020-12-02 20:24 UTC, JavaLavaMT commented on lib/test-support/make-user/index.js
>    });
🏁

2020-12-03 17:12 UTC, JavaLavaMT commented on lib/tasks/notifications/benefits-eligible.js
> +  await Employee.find({ $or: [{ terminatedOn: { $exists: false } }, { terminatedOn: null }] }).populate('company').cursor().eachAsync(async emp =>{
@James1x0 that's not a real link

2020-12-03 17:25 UTC, James1x0 commented on lib/tasks/notifications/benefits-eligible.js
> +  await Employee.find({ $or: [{ terminatedOn: { $exists: false } }, { terminatedOn: null }] }).populate('company').cursor().eachAsync(async emp =>{
https://github.com/associatedemployers/igneous/blob/master/lib/tasks/integrations/benefits-sync.js

2020-12-03 18:12 UTC, JavaLavaMT commented on lib/tasks/notifications/benefits-eligible.js
> +    }
🏁

2020-12-04 14:59 UTC, JavaLavaMT commented on lib/tasks/notifications/hr-enrollment.js
> +  }
🏁

2020-12-04 14:59 UTC, JavaLavaMT commented on lib/tasks/notifications/open-enrollment.js
> +    const openEnrollment = await emp.company.openEnrollment();
🏁

2020-12-04 15:00 UTC, JavaLavaMT commented on lib/tasks/notifications/open-enrollment.js
> +      let nearEnrollment = today || nextMonth ||  nextWeek || lastWeek;
thanks

2020-12-07 16:57 UTC, James1x0 requested changes

2020-12-07 16:57 UTC, James1x0 commented on lib/tasks/notifications/hr-enrollment.js
> +      created:    { $gte: moment().subtract(7, 'days') },
```suggestion
      created:    { $gte: moment().subtract(7, 'days').toDate() },
```

Not sure your test is testing this correctly. 😉

2020-12-07 16:57 UTC, James1x0 commented on lib/tasks/notifications/hr-enrollment.js
> +      $or:        [{ supersedes: null }, { supersedes: { $type: 7 } }],
```suggestion
```

2020-12-07 16:57 UTC, James1x0 commented on lib/models/employee/index.js
> +
```suggestion
```

2020-12-07 16:57 UTC, James1x0 commented on lib/tasks/notifications/benefits-eligible.js
> +    await Employee.find({ terminatedOn: null }).cursor().eachAsync(async (emp) => {
```suggestion
    const lookback = { $lte: moment().add(6, 'months').toDate() };

    await Employee.find({
      terminatedOn: null,
      $or: [{
        created: lookback
      }, {
        hireDate: lookback
      }]
    }).cursor().eachAsync(async (emp) => {
```

Let's optimize this a bit.

2020-12-07 17:35 UTC, James1x0 approved these changes

2020-12-07 17:35 UTC, merged